### PR TITLE
Port to Snorkel Protocol

### PR DESCRIPTION
**Pull request by Timvrakas**
It's called Snorkel because it let's you talk to fish...

### CODE REVIEW

**Comment by mikh3x4** [comment]
Holy shit! Great work. Is there a way I can test without quail?

**Comment by Timvrakas** [comment]
Valve Commanding ✅

Need:
- [x] watchdog timer
- [x] tarring? or load cell calibration state machine?
- [x] I want the valve timer to show up under "Status" when nonzero
- [x] GUI needs to auto-reconnect to quail more agressively
- [ ] verify sensor data with a real quail

It's very close to usable. @rehaanahmad2013 lmk when you're free and I can help get it set up remotely.

**Comment by Timvrakas** [comment]
Watchdog be watching:
image
Valve UI be UI'ing
image

**Comment by Timvrakas** [comment]
Ok I think this is ready for field checkouts and then merging!

**Pull request merged**
